### PR TITLE
Shader metadata extract

### LINKED ISSUE #504: Unable to open some of the vcs files in Aperture Desk Job
### Describe the bug

Loading either dx11 or vulkan throws an exception with some of the shader files. Shaders that do work use version 65.

```
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at ValveResourceFormat.CompiledShader.SfConstraintsBlock.ReadIntRange() in C:\Users\kristi\Documents\GitHub\ValveResourceFormat\ValveResourceFormat\CompiledShader\ShaderDataBlocks.cs:line 373
   at ValveResourceFormat.CompiledShader.SfConstraintsBlock..ctor(ShaderDataReader datareader, Int32 blockIndex) in C:\Users\kristi\Documents\GitHub\ValveResourceFormat\ValveResourceFormat\CompiledShader\ShaderDataBlocks.cs:line 360
   at ValveResourceFormat.CompiledShader.ShaderFile.ParseFile() in C:\Users\kristi\Documents\GitHub\ValveResourceFormat\ValveResourceFormat\CompiledShader\ShaderFile.cs:line 138
   at GUI.Types.Viewers.CompiledShader.GetShaderCollection(String targetFilename, Package vrfPackage) in C:\Users\kristi\Documents\GitHub\ValveResourceFormat\GUI\Types\Viewers\CompiledShader.cs:line 85
   at GUI.Types.Viewers.CompiledShader.Create(VrfGuiContext vrfGuiContext, Byte[] input) in C:\Users\kristi\Documents\GitHub\ValveResourceFormat\GUI\Types\Viewers\CompiledShader.cs:line 47
   at GUI.MainForm.ProcessFile(VrfGuiContext vrfGuiContext, PackageEntry file) in C:\Users\kristi\Documents\GitHub\ValveResourceFormat\GUI\MainForm.cs:line 547
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)```
```

### What Valve game does this happen in

Aperture Desk Job

### Reference file in a Source 2 game

shaders/vfx/vr_complex_vulkan_50_features.vcs
shaders/vfx/vr_depth_only_nonbindless_vulkan_50_features.vcs
shaders/vfx/vr_depth_only_vulkan_50_features.vcs

### Expected behavior

Open and view details

### What version of VRF are you using? On what platform?

0.3.0

### PR DESCRIPTION
**Pull request by kristiker**
* Added appropriate names to a bunch of shader data block members
* Fix loading RTX shader file found in Dota and CS2 - zframes still need fix
* Fix #504 loading some Vertex Shaders in Aperture Desk Job and CS2
* Extracting shader **metadata** back to original source format (vfx)
* Better printouts in shader data viewer.
 
Implements sbox shader_c resources with full compatibility (Closes #461). Not supporting their older vcs files as there is no way to discern those from valve shaders. Even then, library users are able to load those with IsSbox flag set to true.

The extracted shader is just metadata. Not full shader source.

image

### CODE REVIEW

File: GUI/Types/Viewers/CompiledShader.cs [hunk 1]
```diff
@@ -163,30 +175,31 @@ protected virtual void Dispose(bool disposing)
...
             private readonly ShaderFile shaderFile;
-            readonly SortedDictionary<(VcsProgramType, string), ShaderFile> shaderCollection;
+#pragma warning restore CA2213
+            private readonly ShaderCollection shaderCollection;
             private readonly ShaderTabControl tabControl;
             private readonly List<string> relatedFiles = new();
-            public ShaderRichTextBox(ShaderFile shaderFile, ShaderTabControl tabControl,
-                SortedDictionary<(VcsProgramType, string), ShaderFile> shaderCollection = null, bool byteVersion = false) : base()
+            public ShaderRichTextBox(VcsProgramType leadProgramType, ShaderTabControl tabControl,
+                ShaderCollection shaderCollection = null, bool byteVersion = false) : base()
```
Comment (kristiker) [inline GUI/Types/Viewers/CompiledShader.cs:193]: Collection shouldn't be optional/nullable

File: GUI/Types/Viewers/CompiledShader.cs [hunk 2]
```diff
@@ -215,23 +228,23 @@ private void ShaderRichTextBoxLinkClicked(object sender, LinkClickedEventArgs ev
...
                 if (programType != VcsProgramType.Undetermined)
                 {
-                    var shaderFile = shaderCollection[(programType, linkTokens[0])];
+                    var shaderFile = shaderCollection.Get(programType);
                     TabPage newShaderTab = null;
                     if (linkTokens.Length > 1 && linkTokens[1].Equals("bytes", StringComparison.Ordinal))
                     {
                         newShaderTab = new TabPage($"{programType} bytes");
-                        var shaderRichTextBox = new ShaderRichTextBox(shaderFile, tabControl, byteVersion: true);
+                        var shaderRichTextBox = new ShaderRichTextBox(programType, tabControl, byteVersion: true);
```
Comment (kristiker) [inline GUI/Types/Viewers/CompiledShader.cs:239]: Needs to pass the shader collection for it to work

File: ValveResourceFormat/CompiledShader/ZFrameFile.cs [hunk 3]
```diff
@@ -251,12 +251,18 @@ public class ZFrameParam
...
+            public byte HeaderArg { get; }
             public byte[] HeaderCode { get; }
             public int DynExpLen { get; } = -1;
             public byte[] DynExpression { get; }
             public string DynExpEvaluated { get; }
-            public bool HasOperatorVal { get; }
-            public int OperatorVal { get; }
+            public bool? StaticValBool { get; }
+            public int? StaticValInt { get; }
+            public float? StaticValFloat { get; }
```
Comment (kristiker) [inline ValveResourceFormat/CompiledShader/ZFrameFile.cs:263]: These could be just one object.

File: ValveResourceFormat/CompiledShader/Enums/TextureFormat.cs [hunk 4]
```diff
@@ -2,10 +2,67 @@ namespace ValveResourceFormat.CompiledShader;
...
+    DXT3 = 22,
     DXT5 = 23,
-    Unkn27 = 27,
-    BC7 = 86,
+    ATI1N = 24,
+    ATI2N = 25,
+    BC6H = 26,
+    BC7 = 27,
+    DXT5_NM = 28,
+    R8G8B8_ETC2 = 29,
```
Comment (kristiker) [inline ValveResourceFormat/CompiledShader/Enums/TextureFormat.cs:35]: Seems like this enum is only valid for Dota 2.

In Alyx/Sbox/Aperture Desk BC7 has value 86.

File: ValveResourceFormat/CompiledShader/ShaderFile.cs [hunk 5]
```diff
@@ -571,7 +571,6 @@ public byte[] GetDecompressedZFrame()
                         {
                             throw new ShaderParserException("Decompressed zframe doesn't match expected size");
                         }
-                        zstdDecoder.Dispose();
```
Comment (kristiker) [inline ValveResourceFormat/CompiledShader/ShaderFile.cs:565]: Again crashing when multiple threads try to load a zframe. Something with the dictionary.

Comment (robert-hoff) [reply ValveResourceFormat/CompiledShader/ShaderFile.cs:565]: Maybe it's the parser not knowing where the end of the file is

File: ValveResourceFormat/CompiledShader/Enums/TextureFormat.cs (hunk 4 above)
Comment (kristiker) [reply ValveResourceFormat/CompiledShader/Enums/TextureFormat.cs:35]: Older Dota 2 shaders (pcgl v64) don't seem to use this enum either. Therefore I'll make it print these values only with version 66 files.

Should be worth looking up and including the < v66 enum.

Comment (kristiker) [reply ValveResourceFormat/CompiledShader/Enums/TextureFormat.cs:38]: How convenient, I was able to retrieve the older enum from https://asset.party/api/Sandbox.ImageFormat.

File: Tests/VfxEvalTests.cs [hunk 6]
```diff
@@ -296,14 +296,32 @@ public void TestDynamicExpression17()
...
+                "1A 05 07 00 00 00 00 0D 04 0D 00 15 00 07 00 00 AA 42 02 59 00 " +
+                "1A 05 07 00 00 80 3F 0D 04 22 00 2A 00 07 00 00 A0 41 02 59 00 " +
+                "1A 05 07 00 00 00 40 0D 04 37 00 3F 00 07 00 00 A8 41 02 59 00 " +
+                "1A 05 07 00 00 40 40 0D 04 4C 00 54 00 07 00 00 00 00 02 59 00 07 00 00 00 00 00");
+
+            // (F_TEXTURE_FILTERING == 0 ? ANISOTROPIC : (F_TEXTURE_FILTERING == 1 ? BILINEAR : (F_TEXTURE_FILTERING == 2 ? TRILINEAR : (F_TEXTURE_FILTERING == 3 ? POINT : NEAREST))))
+            var expectedResult = "(COND[5]==3) ? 0 : 0";
+
+            Assert.AreEqual(expectedResult, new VfxEval(nestedTernaryBin, omitReturnStatement: true).DynamicExpressionResult);
+        }
```
Comment (kristiker) [inline Tests/VfxEvalTests.cs:323]: There is 4 nested ternary operations here, but VfxEval is only printing one. Added a test with original code and the current output so this can be fixed sometime.

File: ValveResourceFormat/Resource/Enums/ResourceType.cs [hunk 7]
```diff
@@ -123,5 +123,8 @@ public enum ResourceType
 
         [Extension("sbox")] // TODO: Managed resources can have any extension
         SboxManagedResource,
+
+        [Extension("shader")]
```
Comment (xPaw) [inline ValveResourceFormat/Resource/Enums/ResourceType.cs:127]: add a comment that this is for sbox

File: ValveResourceFormat/Utils/UnexpectedMagicException.cs [hunk 8]
```diff
@@ -28,5 +28,21 @@ public UnexpectedMagicException(string message, string magic, string nameofMagic
             Magic = magic;
             MagicNameof = nameofMagic;
         }
+
+        public static void ThrowIfNotEqual(int expectedMagic, int actualMagic, string nameofMagic)
```
Comment (xPaw) [inline ValveResourceFormat/Utils/UnexpectedMagicException.cs:32]: Can we use CallerArgumentExpression? I haven't tried it but I think that should work.

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/caller-argument-expression

Comment (kristiker) [reply ValveResourceFormat/Utils/UnexpectedMagicException.cs:32]: Seems nice. Did a quick test without editing the `Message`:
```
ValveResourceFormat.Utils.UnexpectedMagicException: Assertion failed for variable 'param.Id == 252': 255
```

File: ValveResourceFormat/CompiledShader/ShaderFile.cs (hunk 5 above)
Comment (kristiker) [reply ValveResourceFormat/CompiledShader/ShaderFile.cs:565]: It was a thread safety issue fixed here https://github.com/SteamDatabase/ValveResourceFormat/commit/09598e954d322227fdd09386fb13b9817b874b62
